ALTER TABLE "RatingConfig" ADD COLUMN IF NOT EXISTS "commentLikeWeight" DECIMAL(5,3) NOT NULL DEFAULT 0.02;
ALTER TABLE "RatingConfig" ADD COLUMN IF NOT EXISTS "commentDislikeWeight" DECIMAL(5,3) NOT NULL DEFAULT 0.03;
