#!/usr/bin/env bash
# Setup of the terminal instance (terminal.fomo.spot) on the server. Full runbook: docs/terminal-instance.md
#
# A second INSTANCE of this codebase: own checkout (/opt/fomo-terminal), own .env, own PostgreSQL database and user,
# own pm2 process (fomo-terminal) on its own port, own nginx vhost. Nothing is shared with /opt/fomo (fomo.spot).
#
# Run on the server as a user that may use sudo (postgres, nginx, certbot), from the checkout:
#   git clone https://github.com/viptdv333-boop/fomo.git /opt/fomo-terminal && cd /opt/fomo-terminal
#   bash scripts/terminal-instance-setup.sh all          # env -> db -> install -> vapid -> init -> build -> pm2 -> nginx (prints)
# or step by step:
#   env | db | install | vapid | init | build | pm2 | nginx | certbot | status
#
# Secrets are generated HERE (openssl) and written only to the instance .env (chmod 600); nothing is printed or committed.
# Variables you can override: APP_DIR, PORT, DB_NAME, DB_USER, SITE_HOST, PM2_NAME.
set -euo pipefail

APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PORT="${PORT:-3100}"
DB_NAME="${DB_NAME:-fomo_terminal}"
DB_USER="${DB_USER:-fomo_terminal}"
SITE_HOST="${SITE_HOST:-terminal.fomo.spot}"
PM2_NAME="${PM2_NAME:-fomo-terminal}"
SITE_URL="https://${SITE_HOST}"
ENV_FILE="${APP_DIR}/.env"

say() { printf '\n== %s\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing command: $1" >&2; exit 1; }; }
rand_hex() { openssl rand -hex "${1:-32}"; }
rand_b64() { openssl rand -base64 "${1:-48}" | tr -d '\n'; }

load_env() {
  [ -f "$ENV_FILE" ] || { echo "no $ENV_FILE yet: run the 'env' step first" >&2; exit 1; }
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
}

# --- 1. .env ---------------------------------------------------------------------------------------------------------
step_env() {
  say ".env of the instance"
  need openssl
  if [ -f "$ENV_FILE" ]; then
    echo "$ENV_FILE already exists: left untouched (delete it to regenerate; the generated secrets would change)."
    return
  fi
  local db_pass auth_secret
  db_pass="$(rand_hex 24)"
  auth_secret="$(rand_b64 48)"
  (umask 077; cat > "$ENV_FILE" <<ENVFILE
# .env of the terminal instance (${SITE_URL}). Generated by scripts/terminal-instance-setup.sh. NEVER commit, never copy from /opt/fomo/.env.
# Everything here is independent of fomo.spot: other database, other AUTH_SECRET, other cookies, other keys.

# --- site mode (both, with the same value) --------------------------------------------------------------------------
# SITE_MODE is read at run time by the server; NEXT_PUBLIC_* are inlined at BUILD time (rebuild after changing them).
SITE_MODE=terminal
NEXT_PUBLIC_SITE_MODE=terminal
NEXT_PUBLIC_SITE_URL=${SITE_URL}

# --- server -----------------------------------------------------------------------------------------------------------
PORT=${PORT}
NODE_ENV=production

# --- database: its own PostgreSQL database and user -------------------------------------------------------------------
DATABASE_URL="postgresql://${DB_USER}:${db_pass}@127.0.0.1:5432/${DB_NAME}?schema=public"

# --- authentication: a secret of its own (sessions of fomo.spot are not valid here and the other way round) ------------
AUTH_SECRET=${auth_secret}
NEXTAUTH_SECRET=${auth_secret}
AUTH_URL=${SITE_URL}
NEXTAUTH_URL=${SITE_URL}
# cookies are named "terminal.session-token" / "__Secure-terminal.session-token" (host-only, no Domain); change only if you must
# AUTH_COOKIE_PREFIX=terminal

# --- e-mail (sign-up codes, password reset, notifications): Resend ----------------------------------------------------
# The sender domain must be verified in Resend. Without a key nobody can register (codes are sent by e-mail).
RESEND_API_KEY=
EMAIL_FROM="FOMO Terminal <no-reply@fomo.spot>"

# --- web push: VAPID keys of THIS instance (npx web-push generate-vapid-keys); the public one is a build-time variable ---
NEXT_PUBLIC_VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=
VAPID_SUBJECT="mailto:admin@fomo.spot"

# --- Android push (Firebase project terminal-f7486, package spot.fomo.terminal) -------------------------------------
# service-account key: Firebase console -> Project settings -> Service accounts -> Generate new private key.
# Keep the JSON OUTSIDE the repo, chmod 600. The project id is read from the file.
# FCM_SERVICE_ACCOUNT_FILE=/opt/fomo-terminal-secrets/terminal-f7486-service-account.json

# --- market data (all optional, same meaning as in .env.example) ------------------------------------------------------
# TINKOFF_TOKEN=
# TINKOFF_READONLY_TOKEN=
# ALGOPACK_KEY=
# FMP_API_KEY=

# --- notification channels of the instance (optional; a channel without its variables shows "not configured") ----------
# TELEGRAM_BOT_TOKEN=
# TELEGRAM_BOT_USERNAME=
# TELEGRAM_WEBHOOK_SECRET=
# NOTIFY_PUBLIC_URL=${SITE_URL}

# Background jobs: alerts of the terminal and calendar reminders run inside the server process (set to 0 to switch off).
# ALERT_SCHEDULER=1
# CALENDAR_REMINDERS=1
ENVFILE
  )
  chmod 600 "$ENV_FILE"
  echo "written $ENV_FILE (chmod 600): DATABASE_URL and AUTH_SECRET are generated, the keys are empty — fill RESEND_API_KEY etc. by hand."
}

# --- 2. database ------------------------------------------------------------------------------------------------------
step_db() {
  say "PostgreSQL database and user (needs sudo -u postgres)"
  load_env
  need psql
  # password of the role = the one in DATABASE_URL (parsed, never printed)
  local pass
  pass="$(printf '%s' "$DATABASE_URL" | sed -E 's#^postgresql://[^:]+:([^@]+)@.*#\1#')"
  [ -n "$pass" ] || { echo "cannot read the password from DATABASE_URL" >&2; exit 1; }
  # as postgres: role + database (idempotent). Equivalent manual commands are in docs/terminal-instance.md.
  sudo -u postgres psql -v ON_ERROR_STOP=1 -v pass="$pass" -v dbuser="$DB_USER" -v dbname="$DB_NAME" <<'SQL'
SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'dbuser', :'pass')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'dbuser') \gexec
SELECT format('ALTER ROLE %I PASSWORD %L', :'dbuser', :'pass') \gexec
SELECT format('CREATE DATABASE %I OWNER %I', :'dbname', :'dbuser')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'dbname') \gexec
SQL
  echo "role ${DB_USER} and database ${DB_NAME} are ready."
}

# --- 3. dependencies + schema -----------------------------------------------------------------------------------------
step_install() {
  say "npm install, prisma generate, schema of the empty database"
  load_env
  cd "$APP_DIR"
  need node
  need npm
  if [ -f package-lock.json ]; then npm ci --no-audit --no-fund || npm install --no-audit --no-fund; else npm install --no-audit --no-fund; fi
  npx prisma generate
  # An empty database gets the whole schema straight from prisma/schema.prisma (the Dockerfile / railway.toml do the same).
  # The SQL files in prisma/migrations are idempotent patches for the EXISTING fomo.spot database (applied there with
  # `prisma db execute`); they create no object that is missing from schema.prisma (checked: no extensions, functions,
  # triggers, partial indexes; all 61 indexes are declared in the schema), so db push alone is complete.
  npx prisma db push --skip-generate
}

# --- 3b. web push keys of THIS instance --------------------------------------------------------------------------------
step_vapid() {
  say "VAPID keys (web push) of the instance"
  load_env
  cd "$APP_DIR"
  if [ -n "${VAPID_PRIVATE_KEY:-}" ] && [ -n "${NEXT_PUBLIC_VAPID_PUBLIC_KEY:-}" ]; then echo "already set in $ENV_FILE"; return; fi
  local pair pub priv
  pair="$(node -e "const k=require('web-push').generateVAPIDKeys();process.stdout.write(k.publicKey+' '+k.privateKey)")"
  pub="${pair%% *}"
  priv="${pair##* }"
  sed -i "s|^NEXT_PUBLIC_VAPID_PUBLIC_KEY=.*|NEXT_PUBLIC_VAPID_PUBLIC_KEY=${pub}|; s|^VAPID_PRIVATE_KEY=.*|VAPID_PRIVATE_KEY=${priv}|" "$ENV_FILE"
  echo "generated and written to $ENV_FILE (the public key is a BUILD-time variable: build after this step)"
}

# --- 4. first owner + languages ---------------------------------------------------------------------------------------
step_init() {
  say "languages, site settings and the first OWNER account"
  load_env
  cd "$APP_DIR"
  local email pass1 pass2 name
  email="${OWNER_EMAIL:-}"
  pass1="${OWNER_PASSWORD:-}"
  name="${OWNER_NAME:-}"
  if [ -z "$email" ]; then read -r -p "Owner e-mail: " email; fi
  if [ -z "$pass1" ]; then
    read -r -s -p "Owner password (hidden): " pass1; echo
    read -r -s -p "Repeat: " pass2; echo
    [ "$pass1" = "$pass2" ] || { echo "passwords differ" >&2; exit 1; }
  fi
  if [ -z "$name" ]; then read -r -p "Display name [Owner]: " name || true; fi
  OWNER_EMAIL="$email" OWNER_PASSWORD="$pass1" OWNER_NAME="${name:-Owner}" npx tsx scripts/terminal-instance-init.ts
}

# --- 5. build -----------------------------------------------------------------------------------------------------------
step_build() {
  say "production build (NEXT_PUBLIC_* from .env are baked in)"
  load_env
  cd "$APP_DIR"
  [ "${SITE_MODE:-}" = "terminal" ] && [ "${NEXT_PUBLIC_SITE_MODE:-}" = "terminal" ] || { echo "SITE_MODE / NEXT_PUBLIC_SITE_MODE must both be 'terminal' in $ENV_FILE" >&2; exit 1; }
  [ -d public/app/dl ] || mkdir -p public/app/dl
  npm run build
}

# --- 6. pm2 -------------------------------------------------------------------------------------------------------------
step_pm2() {
  say "pm2 process ${PM2_NAME}"
  load_env
  cd "$APP_DIR"
  need pm2
  # server.ts decides dev / production from NODE_ENV at start-up, so it must be in the pm2 environment
  cat > "${APP_DIR}/ecosystem.terminal.config.cjs" <<ECO
module.exports = {
  apps: [
    {
      name: "${PM2_NAME}",
      cwd: "${APP_DIR}",
      script: "npm",
      args: "start",
      env: { NODE_ENV: "production", PORT: "${PORT}" },
      max_memory_restart: "1500M",
    },
  ],
};
ECO
  if pm2 describe "$PM2_NAME" >/dev/null 2>&1; then pm2 restart "$PM2_NAME" --update-env; else pm2 start "${APP_DIR}/ecosystem.terminal.config.cjs"; fi
  pm2 save
  sleep 3
  curl -fsS -o /dev/null -w "local check http://127.0.0.1:${PORT}/api/version -> %{http_code}\n" "http://127.0.0.1:${PORT}/api/version" || echo "not answering yet: pm2 logs ${PM2_NAME}"
}

# --- 7. nginx -----------------------------------------------------------------------------------------------------------
nginx_conf() {
  cat <<NGINX
# ${SITE_HOST}: second instance of the site, pm2 process ${PM2_NAME} on 127.0.0.1:${PORT}.
# Align the gzip / header lines with /etc/nginx/sites-available/<the fomo.spot vhost> if that one differs.
server {
    listen 80;
    listen [::]:80;
    server_name ${SITE_HOST};
    # certbot (certbot --nginx -d ${SITE_HOST}) adds the 443 server block and the http -> https redirect
    client_max_body_size 25m;

    gzip on;
    gzip_vary on;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml application/json application/javascript application/xml image/svg+xml;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Socket.IO (bell, price stream): path /api/socketio, WebSocket upgrade
    location /api/socketio {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # APK of the Android app (optional: nginx serves it itself, range requests work, no pm2 restart after an update)
    location /app/dl/ {
        alias ${APP_DIR}/public/app/dl/;
        types { application/vnd.android.package-archive apk; application/json json; }
        default_type application/octet-stream;
        add_header Cache-Control "public, max-age=300";
        add_header X-Content-Type-Options nosniff;
        access_log off;
    }

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
    }
}
NGINX
}

step_nginx() {
  say "nginx vhost ${SITE_HOST}"
  if [ "${INSTALL_NGINX:-0}" = "1" ]; then
    nginx_conf | sudo tee "/etc/nginx/sites-available/${SITE_HOST}" >/dev/null
    sudo ln -sf "/etc/nginx/sites-available/${SITE_HOST}" "/etc/nginx/sites-enabled/${SITE_HOST}"
    echo "installed: /etc/nginx/sites-available/${SITE_HOST} (+ symlink in sites-enabled)."
  else
    nginx_conf
    echo
    echo "# ^ printed only. Install it with: INSTALL_NGINX=1 bash scripts/terminal-instance-setup.sh nginx"
  fi
  echo "# then:  sudo nginx -t && sudo systemctl reload nginx   and   bash scripts/terminal-instance-setup.sh certbot"
}

step_certbot() {
  say "certificate (DNS A/AAAA record of ${SITE_HOST} must already point to this server)"
  need certbot
  local args=(--nginx -d "$SITE_HOST" --redirect --agree-tos --no-eff-email)
  if [ -n "${CERTBOT_EMAIL:-}" ]; then args+=(-m "$CERTBOT_EMAIL"); else args+=(--register-unsafely-without-email); fi
  sudo certbot "${args[@]}"
  sudo nginx -t && sudo systemctl reload nginx
}

step_status() {
  say "status"
  pm2 describe "$PM2_NAME" 2>/dev/null | grep -E "status|restarts|uptime" || echo "pm2 process ${PM2_NAME} not found"
  curl -fsS -o /dev/null -w "http://127.0.0.1:${PORT}/ -> %{http_code}\n" "http://127.0.0.1:${PORT}/" || true
  curl -fsS -o /dev/null -w "${SITE_URL}/ -> %{http_code}\n" "${SITE_URL}/" || true
}

case "${1:-help}" in
  env) step_env ;;
  db) step_db ;;
  install) step_install ;;
  vapid) step_vapid ;;
  init) step_init ;;
  build) step_build ;;
  pm2) step_pm2 ;;
  nginx) step_nginx ;;
  certbot) step_certbot ;;
  status) step_status ;;
  all) step_env; step_db; step_install; step_vapid; step_init; step_build; step_pm2; step_nginx ;;
  *) sed -n '2,16p' "$0" ;;
esac
