import { eventId } from "./normalize";
import { addDays, tzOffsetMs } from "./time";
import type { CalEvent } from "./types";

/*
 * COMMODITIES AND AGRICULTURE LAYER (category "commodity"), merged into every calendar answer next to the MOEX layer.
 * TradingView's feed has no crop / soft-commodity reports at all (only "WASDE Report" and "Global Dairy Trade Price Index"), so the
 * SCHEDULED release dates of the reports that move grain, oilseed, soft, palm-oil and livestock markets are kept here as a static,
 * hand-verified table. There is no live feed: the table is the source of truth.
 *
 * Every date comes from the issuer's own published calendar (the URL is in `src` of the series and in each event's description) or
 * from a rule the issuer states. Each item is either
 *   - EXACT (default): the date is published by the issuer (a few are marked `tent`: the issuer calls the date tentative), or
 *   - APPROX (`a: true`): derived by a rule of thumb (MPOB "about the 10th", cargo-surveyor data on the 10th / 15th / 20th / 25th,
 *     USDA Crop Progress of the next season, holiday-week Export Sales). Approx events carry «(ориентировочно)» in the title and
 *     their importance is capped at 2.
 *
 * HOW AND WHEN TO REFRESH (a yearly chore, ~30 minutes; run `npx tsx scripts/check-calendar-commodities.ts` afterwards):
 *   - USDA WASDE: usda.gov/oce/commodity/wasde, line «20xx WASDE Release Dates» (published for the whole year; the 2027 list was not out in Oct 2026).
 *   - USDA NASS (Crop Progress, Grain Stocks, Prospective Plantings, Acreage, Hogs and Pigs, Cattle on Feed, Cold Storage): the ESMIS
 *     release calendar esmis.nal.usda.gov/release-calendar (the page embeds the whole year as JSON in drupalSettings ->
 *     fullcalendar -> eventSources; NASS publishes next year's calendar in the autumn). Replace the lists in NASS_* below, then drop
 *     the approx Crop Progress rule for that year (CROP_PROGRESS_RULE_FROM_YEAR).
 *   - Cocoa grindings: eurococoa.com/all-about-grind-stats, candyusa.com/cocoa-grinds-report (PDF «report schedule»), cocoaasia.org/grinding-figures.
 *   - CONAB: the PDF «Calendário de Safras e Prohort» linked from gov.br/conab (grains, coffee, sugarcane), published in January.
 *   - Statistics Canada: www150.statcan.gc.ca/n1/dai-quo/ssi/homepage/schedule-key_indicators-eng.json (all future «principal field crop» rows).
 *   - JRC MARS Bulletin: the «Upcoming issues» line on joint-research-centre.ec.europa.eu/monitoring-agricultural-resources-mars/jrc-mars-bulletin_en.
 *   - USDA FAS Coffee: World Markets and Trade: the «next release of this publication will be on ...» sentence in apps.fas.usda.gov/psdonline/circulars/coffee.pdf.
 *   - Approx series (MPOB, cargo surveyors, Export Sales, Crop Progress 2027) are generated by rules below up to MAX_RULE_DATE.
 * NOT verified and therefore NOT here: ICCO quarterly bulletin and market report, ICO Coffee Market Report, UNICA fortnight reports, ISO,
 * Strategie Grains, Ivory Coast / Ghana farmgate prices, USDA FAS Sugar: World Markets and Trade (none of them publishes dates in advance).
 *
 * Times: only where the issuer states one (local zone in `tz`, converted to UTC with the real DST rules); otherwise the event is all-day.
 */

export type CommodityLang = "ru" | "en" | "cn";

export interface Item {
  /** local date YYYY-MM-DD in the issuer's zone */
  d: string;
  /** local clock time HH:MM (series.tz), overrides series.t */
  t?: string;
  /** period label appended to the title (ru / en) */
  q?: string;
  qe?: string;
  /** approximate date (rule of thumb) */
  a?: boolean;
  /** the issuer calls the date tentative */
  tent?: boolean;
  /** importance override */
  imp?: 1 | 2 | 3;
}

interface Series {
  id: string;
  /** glossary key (glossary-rules.ts) */
  gk: string;
  country: string;
  currency: string;
  tags: string[];
  impact: 1 | 2 | 3;
  ru: string;
  en: string;
  /** IANA zone of the stated clock time ("" = all-day events) */
  tz: string;
  /** default clock time HH:MM */
  t?: string;
  /** publisher shown as the origin */
  org: string;
  /** official source of the dates */
  src: string;
  noteRu: string;
  noteEn: string;
  items: Item[];
}

const NY = "America/New_York";
const MAX_RULE_DATE = "2027-12-31";
const CROP_PROGRESS_RULE_FROM_YEAR = 2027;

const dates = (list: string, extra: Partial<Item> = {}): Item[] => list.split(/\s+/).filter(Boolean).map((d) => ({ d, ...extra }));

/* ───────────── calendar arithmetic (dates are YYYY-MM-DD strings, zone independent) ───────────── */

const dow = (d: string): number => new Date(`${d}T00:00:00Z`).getUTCDay(); // 0 Sunday
const iso = (y: number, m: number, d: number): string => new Date(Date.UTC(y, m - 1, d)).toISOString().slice(0, 10);

function nthWeekday(y: number, m: number, wd: number, n: number): string {
  const first = dow(iso(y, m, 1));
  return iso(y, m, 1 + ((wd - first + 7) % 7) + (n - 1) * 7);
}
function lastWeekday(y: number, m: number, wd: number): string {
  const last = addDays(iso(y, m + 1, 1), -1);
  return addDays(last, -((dow(last) - wd + 7) % 7));
}

/** US federal holidays as observed (a Saturday holiday is observed on Friday, a Sunday one on Monday), years y-1..y+1 merged. */
export function usFederalHolidays(y: number): Set<string> {
  const out = new Set<string>();
  for (const yy of [y - 1, y, y + 1]) {
    const fixed = [iso(yy, 1, 1), iso(yy, 6, 19), iso(yy, 7, 4), iso(yy, 11, 11), iso(yy, 12, 25)];
    for (const f of fixed) out.add(dow(f) === 6 ? addDays(f, -1) : dow(f) === 0 ? addDays(f, 1) : f);
    out.add(nthWeekday(yy, 1, 1, 3)); // Martin Luther King Jr. Day
    out.add(nthWeekday(yy, 2, 1, 3)); // Presidents Day
    out.add(lastWeekday(yy, 5, 1)); // Memorial Day
    out.add(nthWeekday(yy, 9, 1, 1)); // Labor Day
    out.add(nthWeekday(yy, 10, 1, 2)); // Columbus Day
    out.add(nthWeekday(yy, 11, 4, 4)); // Thanksgiving
  }
  return out;
}

/* ───────────── USDA ───────────── */

/** WASDE: official list of usda.gov/oce/commodity/wasde («In 2026 the WASDE report will be released on ...»), 12:00 ET. 2027 not published yet. */
export const WASDE_2026 = "2026-01-12 2026-02-10 2026-03-10 2026-04-09 2026-05-12 2026-06-11 2026-07-10 2026-08-12 2026-09-11 2026-10-09 2026-11-10 2026-12-10";

/** NASS release calendar (ESMIS), 2026 only; 12:00 ET for the crop reports, 15:00 ET for the livestock ones. */
const NASS_GRAIN_STOCKS = "2026-01-12 2026-03-31 2026-06-30 2026-09-30";
const NASS_PLANTINGS = "2026-03-31";
const NASS_ACREAGE = "2026-06-30";
const NASS_HOGS = "2026-03-26 2026-06-25 2026-09-24 2026-12-23";
const NASS_COF = "2026-01-23 2026-02-20 2026-03-20 2026-04-17 2026-05-22 2026-06-18 2026-07-24 2026-08-21 2026-09-18 2026-10-23 2026-11-20 2026-12-18";
const NASS_COLD = "2026-01-23 2026-02-24 2026-03-24 2026-04-24 2026-05-22 2026-06-25 2026-07-24 2026-08-24 2026-09-25 2026-10-23 2026-11-24 2026-12-23";
/** Crop Progress 2026 as listed by NASS (holiday weeks move to Tuesday: May 26, Sep 8, Oct 13). */
export const NASS_CROP_PROGRESS_2026 =
  "2026-04-06 2026-04-13 2026-04-20 2026-04-27 2026-05-04 2026-05-11 2026-05-18 2026-05-26 2026-06-01 2026-06-08 2026-06-15 2026-06-22 2026-06-29 2026-07-06 2026-07-13 2026-07-20 2026-07-27 2026-08-03 2026-08-10 2026-08-17 2026-08-24 2026-08-31 2026-09-08 2026-09-14 2026-09-21 2026-09-28 2026-10-05 2026-10-13 2026-10-19 2026-10-26 2026-11-02 2026-11-09 2026-11-16 2026-11-23 2026-11-30";

const cpImpact = (d: string): 1 | 2 => (+d.slice(5, 7) >= 6 && +d.slice(5, 7) <= 9 ? 2 : 1);

/** Crop Progress of a season not yet in the NASS calendar: Mondays from the first Monday of April to the last Monday of November, a holiday Monday moves to Tuesday (rule seen in 2020-2026). */
export function cropProgressRule(year: number): Item[] {
  const out: Item[] = [];
  const first = nthWeekday(year, 4, 1, 1);
  const last = lastWeekday(year, 11, 1);
  const hol = usFederalHolidays(year);
  for (let d = first; d <= last; d = addDays(d, 7)) {
    const when = hol.has(d) ? addDays(d, 1) : d;
    out.push({ d: when, a: true, imp: cpImpact(when) });
  }
  return out;
}

/** Export Sales: Thursdays 08:30 ET (FAS: «unless a change is announced»); when the Friday before or Monday-Thursday of the release week is a federal holiday the summary comes out on Friday. */
export function exportSalesRule(from: string, to: string): Item[] {
  const out: Item[] = [];
  let d = from;
  while (dow(d) !== 4) d = addDays(d, 1);
  const hol = new Set<string>([...usFederalHolidays(+from.slice(0, 4)), ...usFederalHolidays(+to.slice(0, 4))]);
  for (; d <= to; d = addDays(d, 7)) {
    const shifted = [-6, -3, -2, -1, 0].some((k) => hol.has(addDays(d, k)));
    // the Friday itself may be a holiday (Dec 31 -> Jan 1): then the Thursday stays, but the date is a guess
    out.push(shifted ? { d: hol.has(addDays(d, 1)) ? d : addDays(d, 1), a: true } : { d });
  }
  return out;
}

/* ───────────── monthly rules (approx) ───────────── */

const MONTHS_RU = ["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"];
const MONTHS_EN = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

const nextWeekday = (d: string): string => {
  let x = d;
  while (dow(x) === 0 || dow(x) === 6) x = addDays(x, 1);
  return x;
};

/** MPOB publishes on about the 10th of the month (a weekend moves to Monday); the data are those of the previous month. Future months only. */
function mpobRule(from: string, to: string): Item[] {
  const out: Item[] = [];
  for (let y = +from.slice(0, 4); y <= +to.slice(0, 4); y++) {
    for (let m = 1; m <= 12; m++) {
      const d = nextWeekday(iso(y, m, 10));
      if (d < from || d > to) continue;
      const prev = (m + 10) % 12;
      out.push({ d, a: true, q: `за ${MONTHS_RU[prev]}`, qe: `${MONTHS_EN[prev]} data` });
    }
  }
  return out;
}

/** Cargo-surveyor export data (ITS / AmSpec) of the 1st-10th, 1st-15th, 1st-20th and 1st-25th of the month: published the same evening / next morning, no official calendar. */
function cargoRule(from: string, to: string): Item[] {
  const out: Item[] = [];
  for (let y = +from.slice(0, 4); y <= +to.slice(0, 4); y++) {
    for (let m = 1; m <= 12; m++) {
      for (const day of [10, 15, 20, 25]) {
        const d = nextWeekday(iso(y, m, day));
        if (d < from || d > to) continue;
        out.push({ d, a: true, q: `1–${day} числа`, qe: `1st-${day}th` });
      }
    }
  }
  return out;
}

/* ───────────── the table ───────────── */

const WASDE_URL = "https://www.usda.gov/oce/commodity/wasde";
const ESMIS_URL = "https://esmis.nal.usda.gov/release-calendar";
const CONAB_URL = "https://www.gov.br/conab/pt-br/assuntos/imagens/calendario-de-safras-e-prohort-2026-interativo.pdf";
const STATCAN_URL = "https://www150.statcan.gc.ca/n1/dai-quo/cal1-eng.htm";

const NASS = (id: string, gk: string, ru: string, en: string, tags: string[], impact: 1 | 2 | 3, time: string, list: string, noteRu: string, noteEn: string, extra: Partial<Series> = {}): Series => ({
  id, gk, country: "US", currency: "USD", tags, impact, ru, en, tz: NY, t: time, org: "USDA NASS", src: ESMIS_URL, noteRu, noteEn, items: dates(list), ...extra,
});

export const SERIES: Series[] = [
  {
    id: "wasde", gk: "agro.wasde", country: "US", currency: "USD", tags: ["wheat", "corn", "soy", "cotton", "sugar"], impact: 3,
    ru: "США: Отчёт USDA WASDE (мировой баланс зерна и масличных)", en: "US: USDA WASDE report (world supply and demand)", tz: NY, t: "12:00", org: "USDA WAOB", src: WASDE_URL,
    noteRu: "Официальная дата выхода WASDE, 12:00 по Нью-Йорку. В тот же день выходит Crop Production.", noteEn: "Official WASDE release date, 12:00 ET (Crop Production comes out the same day).",
    items: dates(WASDE_2026),
  },
  {
    id: "cropprogress", gk: "agro.cropprogress", country: "US", currency: "USD", tags: ["corn", "soy", "wheat", "cotton"], impact: 2,
    ru: "США: Отчёт USDA Crop Progress (состояние посевов)", en: "US: USDA Crop Progress", tz: NY, t: "16:00", org: "USDA NASS", src: ESMIS_URL,
    noteRu: "Еженедельный отчёт по понедельникам в 16:00 по Нью-Йорку (в праздничную неделю — во вторник), сезон с апреля по ноябрь.", noteEn: "Weekly, Mondays 16:00 ET (Tuesday after a holiday), April to November.",
    items: [...NASS_CROP_PROGRESS_2026.split(" ").map((d) => ({ d, imp: cpImpact(d) })), ...cropProgressRule(CROP_PROGRESS_RULE_FROM_YEAR)],
  },
  {
    id: "exportsales", gk: "agro.exportsales", country: "US", currency: "USD", tags: ["wheat", "corn", "soy", "cotton"], impact: 1,
    ru: "США: Экспортные продажи USDA (Export Sales)", en: "US: USDA Export Sales", tz: NY, t: "08:30", org: "USDA FAS", src: "https://www.fas.usda.gov/programs/export-sales-reporting-program",
    noteRu: "Еженедельная сводка FAS: по четвергам в 08:30 по Нью-Йорку, если не объявлено иное; в праздничную неделю сводка выходит в пятницу.", noteEn: "Weekly FAS summary: Thursdays 08:30 ET unless announced otherwise; Friday in holiday weeks.",
    items: exportSalesRule("2026-01-01", MAX_RULE_DATE),
  },
  NASS("grainstocks", "agro.grainstocks", "США: Отчёт USDA Grain Stocks (запасы зерна)", "US: USDA Grain Stocks", ["corn", "soy", "wheat"], 3, "12:00", NASS_GRAIN_STOCKS,
    "Квартальные запасы зерна и сои (NASS), 12:00 по Нью-Йорку. Дата из календаря NASS.", "Quarterly grain and soybean stocks (NASS), 12:00 ET. Date from the NASS calendar."),
  NASS("plantings", "agro.plantings", "США: Отчёт USDA Prospective Plantings (планы посевов)", "US: USDA Prospective Plantings", ["corn", "soy", "wheat", "cotton"], 3, "12:00", NASS_PLANTINGS,
    "Опрос фермеров о планах посева (NASS), 12:00 по Нью-Йорку.", "Farmers' planting intentions (NASS), 12:00 ET."),
  NASS("acreage", "agro.acreage", "США: Отчёт USDA Acreage (посевные площади)", "US: USDA Acreage", ["corn", "soy", "wheat", "cotton"], 3, "12:00", NASS_ACREAGE,
    "Фактические посевные площади (NASS), 12:00 по Нью-Йорку.", "Actual planted acreage (NASS), 12:00 ET."),
  NASS("hogs", "agro.hogs", "США: Отчёт USDA Hogs and Pigs (поголовье свиней)", "US: USDA Hogs and Pigs", ["cattle", "corn", "soy"], 2, "15:00", NASS_HOGS,
    "Квартальное поголовье свиней (NASS), 15:00 по Нью-Йорку.", "Quarterly hog inventory (NASS), 15:00 ET."),
  NASS("cof", "agro.cof", "США: Отчёт USDA Cattle on Feed (скот на откорме)", "US: USDA Cattle on Feed", ["cattle", "corn"], 2, "15:00", NASS_COF,
    "Ежемесячные данные о скоте на откорме (NASS), 15:00 по Нью-Йорку.", "Monthly cattle on feed (NASS), 15:00 ET."),
  NASS("coldstorage", "agro.coldstorage", "США: Отчёт USDA Cold Storage (запасы мяса и молочных продуктов)", "US: USDA Cold Storage", ["cattle"], 1, "15:00", NASS_COLD,
    "Ежемесячные запасы мяса и молочной продукции на холодильных складах (NASS), 15:00 по Нью-Йорку.", "Monthly meat and dairy stocks in cold storage (NASS), 15:00 ET."),
  {
    id: "usdacoffee", gk: "agro.usda.coffee", country: "US", currency: "USD", tags: ["coffee"], impact: 2,
    ru: "США: Отчёт USDA «Кофе: мировые рынки и торговля»", en: "US: USDA Coffee: World Markets and Trade", tz: "", org: "USDA FAS", src: "https://apps.fas.usda.gov/psdonline/circulars/coffee.pdf",
    noteRu: "Полугодовой отчёт FAS; дата названа в самом отчёте («next release ... December 16, 2026»), время не указано.", noteEn: "Semi-annual FAS report; the date is stated in the report itself (next release December 16, 2026), no time given.",
    items: dates("2026-12-16"),
  },
  /* cocoa grindings: three associations */
  {
    id: "cocoa-eca", gk: "agro.cocoa.grind", country: "EU", currency: "EUR", tags: ["cocoa"], impact: 3,
    ru: "Какао: перемалывание в Европе (ECA)", en: "Cocoa: Europe grindings (ECA)", tz: "Europe/Brussels", t: "08:00", org: "ECA", src: "https://www.eurococoa.com/all-about-grind-stats/",
    noteRu: "Квартальная статистика Европейской ассоциации какао, 08:00 по Брюсселю. Даты Q1 и Q2 подтверждены, Q3 и Q4 ассоциация называет предварительными.", noteEn: "Quarterly statistics of the European Cocoa Association, 08:00 Brussels time. Q1-Q2 dates are confirmed, Q3-Q4 are called tentative by the ECA.",
    items: [
      { d: "2026-04-16", q: "1 кв. 2026", qe: "Q1 2026" }, { d: "2026-07-16", q: "2 кв. 2026", qe: "Q2 2026" },
      { d: "2026-10-15", q: "3 кв. 2026", qe: "Q3 2026", tent: true }, { d: "2027-01-21", q: "4 кв. 2026", qe: "Q4 2026", tent: true },
    ],
  },
  {
    id: "cocoa-nca", gk: "agro.cocoa.grind", country: "US", currency: "USD", tags: ["cocoa"], impact: 2,
    ru: "Какао: перемалывание в Северной Америке (NCA)", en: "Cocoa: North America grindings (NCA)", tz: NY, t: "16:00", org: "NCA", src: "https://candyusa.com/cocoa-grinds-report/",
    noteRu: "Квартальный отчёт Национальной ассоциации кондитеров США, публикуется через ICE Futures в 16:00 (время в расписании NCA без указания пояса, принято нью-йоркское).", noteEn: "Quarterly report of the National Confectioners Association, released by ICE Futures at 4:00 pm (the NCA schedule gives no time zone; New York time assumed).",
    items: [
      { d: "2026-04-16", q: "1 кв. 2026", qe: "Q1 2026" }, { d: "2026-07-16", q: "2 кв. 2026", qe: "Q2 2026" },
      { d: "2026-10-15", q: "3 кв. 2026", qe: "Q3 2026" }, { d: "2027-01-21", q: "4 кв. 2026", qe: "Q4 2026" },
    ],
  },
  {
    id: "cocoa-caa", gk: "agro.cocoa.grind", country: "SG", currency: "SGD", tags: ["cocoa"], impact: 2,
    ru: "Какао: перемалывание в Азии (CAA)", en: "Cocoa: Asia grindings (CAA)", tz: "Asia/Singapore", t: "16:00", org: "CAA", src: "https://www.cocoaasia.org/grinding-figures",
    noteRu: "Квартальная статистика Азиатской ассоциации какао; публикуется после 16:00 по Сингапуру. Дата на 2027 год ещё не объявлена.", noteEn: "Quarterly statistics of the Cocoa Association of Asia, published after 4 pm Singapore time. No 2027 date announced yet.",
    items: [
      { d: "2026-01-16", q: "4 кв. 2025", qe: "Q4 2025" }, { d: "2026-04-16", q: "1 кв. 2026", qe: "Q1 2026" },
      { d: "2026-07-16", q: "2 кв. 2026", qe: "Q2 2026" }, { d: "2026-10-15", q: "3 кв. 2026", qe: "Q3 2026" },
    ],
  },
  /* CONAB (Brazil) */
  {
    id: "conab-grains", gk: "agro.conab.grains", country: "BR", currency: "BRL", tags: ["soy", "corn", "cotton"], impact: 2,
    ru: "Бразилия: оценка урожая зерновых от CONAB", en: "Brazil: CONAB grain crop survey", tz: "", org: "CONAB", src: CONAB_URL,
    noteRu: "Дата из официального календаря CONAB, время не указано.", noteEn: "Date from the official CONAB calendar, no time given.",
    items: [
      { d: "2026-01-15", q: "4-й обзор 2025/26", qe: "survey 4, 2025/26" }, { d: "2026-02-12", q: "5-й обзор 2025/26", qe: "survey 5, 2025/26" }, { d: "2026-03-13", q: "6-й обзор 2025/26", qe: "survey 6, 2025/26" },
      { d: "2026-04-14", q: "7-й обзор 2025/26", qe: "survey 7, 2025/26" }, { d: "2026-05-14", q: "8-й обзор 2025/26", qe: "survey 8, 2025/26" }, { d: "2026-06-11", q: "9-й обзор 2025/26", qe: "survey 9, 2025/26" },
      { d: "2026-07-14", q: "10-й обзор 2025/26", qe: "survey 10, 2025/26" }, { d: "2026-08-13", q: "11-й обзор 2025/26", qe: "survey 11, 2025/26" }, { d: "2026-09-15", q: "12-й обзор 2025/26", qe: "survey 12, 2025/26" },
      { d: "2026-10-15", q: "1-й обзор 2026/27", qe: "survey 1, 2026/27" }, { d: "2026-11-13", q: "2-й обзор 2026/27", qe: "survey 2, 2026/27" }, { d: "2026-12-15", q: "3-й обзор 2026/27", qe: "survey 3, 2026/27" },
      { d: "2027-01-14", q: "4-й обзор 2026/27", qe: "survey 4, 2026/27" },
    ],
  },
  {
    id: "conab-coffee", gk: "agro.conab.coffee", country: "BR", currency: "BRL", tags: ["coffee"], impact: 2,
    ru: "Бразилия: оценка урожая кофе от CONAB", en: "Brazil: CONAB coffee crop survey", tz: "", org: "CONAB", src: CONAB_URL,
    noteRu: "Дата из официального календаря CONAB, время не указано.", noteEn: "Date from the official CONAB calendar, no time given.",
    items: [
      { d: "2026-02-05", q: "1-й обзор 2026", qe: "survey 1, 2026" }, { d: "2026-05-21", q: "2-й обзор 2026", qe: "survey 2, 2026" },
      { d: "2026-09-24", q: "3-й обзор 2026", qe: "survey 3, 2026" }, { d: "2027-01-07", q: "4-й обзор 2026", qe: "survey 4, 2026" },
    ],
  },
  {
    id: "conab-cane", gk: "agro.conab.cane", country: "BR", currency: "BRL", tags: ["sugar"], impact: 1,
    ru: "Бразилия: оценка урожая сахарного тростника от CONAB", en: "Brazil: CONAB sugarcane crop survey", tz: "", org: "CONAB", src: CONAB_URL,
    noteRu: "Дата из официального календаря CONAB, время не указано.", noteEn: "Date from the official CONAB calendar, no time given.",
    items: [
      { d: "2026-04-16", q: "4-й обзор 2025/26", qe: "survey 4, 2025/26" }, { d: "2026-04-28", q: "1-й обзор 2026/27", qe: "survey 1, 2026/27" },
      { d: "2026-08-20", q: "2-й обзор 2026/27", qe: "survey 2, 2026/27" }, { d: "2026-12-22", q: "3-й обзор 2026/27", qe: "survey 3, 2026/27" },
    ],
  },
  /* Statistics Canada, 08:30 ET (The Daily is released at 8:30 a.m. Eastern) */
  {
    id: "statcan-areas", gk: "agro.statcan", country: "CA", currency: "CAD", tags: ["wheat", "agro", "cad"], impact: 2,
    ru: "Канада: посевные площади зерновых и масличных (Statistics Canada)", en: "Canada: principal field crop areas (Statistics Canada)", tz: NY, t: "08:30", org: "Statistics Canada", src: STATCAN_URL,
    noteRu: "Дата из официального расписания выпусков Statistics Canada; The Daily выходит в 08:30 по Оттаве.", noteEn: "Date from the Statistics Canada release schedule; The Daily comes out at 8:30 a.m. Eastern.",
    items: [{ d: "2026-03-05", q: "намерения 2026", qe: "2026 intentions" }, { d: "2026-06-30", q: "июнь 2026", qe: "June 2026" }, { d: "2027-03-04", q: "намерения 2027", qe: "2027 intentions" }],
  },
  {
    id: "statcan-stocks", gk: "agro.statcan", country: "CA", currency: "CAD", tags: ["wheat", "agro", "cad"], impact: 2,
    ru: "Канада: запасы зерновых и масличных (Statistics Canada)", en: "Canada: stocks of principal field crops (Statistics Canada)", tz: NY, t: "08:30", org: "Statistics Canada", src: STATCAN_URL,
    noteRu: "Дата из официального расписания выпусков Statistics Canada; The Daily выходит в 08:30 по Оттаве.", noteEn: "Date from the Statistics Canada release schedule; The Daily comes out at 8:30 a.m. Eastern.",
    items: [
      { d: "2026-02-06", q: "на 31 декабря 2025", qe: "as of Dec 31, 2025" }, { d: "2026-05-06", q: "на 31 марта 2026", qe: "as of Mar 31, 2026" },
      { d: "2026-09-09", q: "на 31 июля 2026", qe: "as of Jul 31, 2026" }, { d: "2027-02-05", q: "на 31 декабря 2026", qe: "as of Dec 31, 2026" },
    ],
  },
  {
    id: "statcan-prod", gk: "agro.statcan", country: "CA", currency: "CAD", tags: ["wheat", "agro", "cad"], impact: 2,
    ru: "Канада: оценка урожая зерновых и масличных (Statistics Canada)", en: "Canada: production of principal field crops (Statistics Canada)", tz: NY, t: "08:30", org: "Statistics Canada", src: STATCAN_URL,
    noteRu: "Дата из официального расписания выпусков Statistics Canada; The Daily выходит в 08:30 по Оттаве.", noteEn: "Date from the Statistics Canada release schedule; The Daily comes out at 8:30 a.m. Eastern.",
    items: [{ d: "2026-09-16", q: "модельная оценка, август 2026", qe: "model-based, August 2026" }, { d: "2026-12-04", q: "ноябрь 2026", qe: "November 2026" }],
  },
  {
    id: "mars", gk: "agro.mars", country: "EU", currency: "EUR", tags: ["wheat", "corn"], impact: 1,
    ru: "ЕС: бюллетень мониторинга посевов JRC MARS", en: "EU: JRC MARS crop monitoring bulletin", tz: "", org: "EC JRC", src: "https://joint-research-centre.ec.europa.eu/monitoring-agricultural-resources-mars/jrc-mars-bulletin_en",
    noteRu: "Даты ближайших выпусков названы на странице бюллетеня JRC; время не указано.", noteEn: "Dates of the upcoming issues are given on the JRC bulletin page; no time stated.",
    items: dates("2026-10-26 2026-11-23"),
  },
  /* approximate series */
  {
    id: "mpob", gk: "agro.mpob", country: "MY", currency: "MYR", tags: ["palm", "soy"], impact: 2,
    ru: "Малайзия: данные MPOB по пальмовому маслу", en: "Malaysia: MPOB palm oil data", tz: "Asia/Kuala_Lumpur", t: "12:30", org: "MPOB", src: "https://bepi.mpob.gov.my/",
    noteRu: "MPOB публикует данные за прошлый месяц около 10-го числа в 12:30 по Малайзии; выходной день сдвигает выход на понедельник (малайзийские праздники не учтены).", noteEn: "MPOB publishes last month's data on about the 10th at 12:30 Malaysia time; a weekend moves it to Monday (Malaysian public holidays are not modelled).",
    items: mpobRule("2026-10-01", MAX_RULE_DATE),
  },
  {
    id: "palmcargo", gk: "agro.palm.cargo", country: "MY", currency: "MYR", tags: ["palm"], impact: 1,
    ru: "Малайзия: экспорт пальмового масла по данным сюрвейеров", en: "Malaysia: palm oil exports by cargo surveyors", tz: "", org: "ITS / AmSpec", src: "https://bepi.mpob.gov.my/",
    noteRu: "Независимые сюрвейеры (ITS, AmSpec) обычно публикуют экспорт нарастающим итогом 10-го, 15-го, 20-го и 25-го числа; официального календаря нет, источник дат — сложившаяся практика.", noteEn: "Independent surveyors (ITS, AmSpec) usually publish month-to-date exports on the 10th, 15th, 20th and 25th; there is no official calendar, the dates follow market practice.",
    items: cargoRule("2026-10-01", MAX_RULE_DATE),
  },
];

/* ───────────── building events ───────────── */

export function wallToUtc(date: string, hm: string, zone: string): number {
  const [y, m, d] = date.split("-").map(Number);
  const [h, mi] = hm.split(":").map(Number);
  const wall = Date.UTC(y, m - 1, d, h, mi);
  let ts = wall - tzOffsetMs(wall, zone);
  ts = wall - tzOffsetMs(ts, zone); // second pass settles the DST edge
  return ts;
}

export interface ScheduledItem {
  series: string;
  gk: string;
  /** local date in the issuer's zone */
  date: string;
  ts: number;
  allDay: boolean;
  approx: boolean;
  tentative: boolean;
  impact: 1 | 2 | 3;
  src: string;
  tz: string;
  time: string | null;
}

/** The raw schedule (for the check script): every item with its instant, importance and exactness. */
export function commoditySchedule(): ScheduledItem[] {
  const out: ScheduledItem[] = [];
  for (const s of SERIES) {
    for (const it of s.items) {
      const hm = it.t ?? s.t ?? null;
      const allDay = !s.tz || !hm;
      const ts = allDay ? Date.parse(`${it.d}T00:00:00Z`) : wallToUtc(it.d, hm!, s.tz);
      const base = it.imp ?? s.impact;
      out.push({ series: s.id, gk: s.gk, date: it.d, ts, allDay, approx: !!it.a, tentative: !!it.tent, impact: (it.a ? Math.min(base, 2) : base) as 1 | 2 | 3, src: s.src, tz: s.tz, time: allDay ? null : hm, });
    }
  }
  return out.sort((a, b) => a.ts - b.ts);
}

const SUFFIX = { ru: " (ориентировочно)", en: " (approx.)" } as const;

function buildAll(lang: "ru" | "en"): CalEvent[] {
  const out: CalEvent[] = [];
  for (const s of SERIES) {
    for (const it of s.items) {
      const hm = it.t ?? s.t ?? null;
      const allDay = !s.tz || !hm;
      const ts = allDay ? Date.parse(`${it.d}T00:00:00Z`) : wallToUtc(it.d, hm!, s.tz);
      const q = lang === "ru" ? it.q : it.qe;
      const title = `${lang === "ru" ? s.ru : s.en}${q ? `, ${q}` : ""}${it.a ? SUFFIX[lang] : ""}`;
      const flags =
        lang === "ru"
          ? `${it.a ? "Дата ориентировочная: выведена по правилу, издатель её заранее не объявлял. " : ""}${it.tent ? "Дата объявлена организацией как предварительная. " : ""}`
          : `${it.a ? "Approximate date: derived from a rule, not announced by the issuer. " : ""}${it.tent ? "The issuer calls this date tentative. " : ""}`;
      const base = it.imp ?? s.impact;
      out.push({
        id: eventId(ts, s.country, title),
        ts,
        allDay,
        country: s.country,
        currency: s.currency,
        event: title,
        category: "commodity",
        impact: (it.a ? Math.min(base, 2) : base) as 1 | 2 | 3,
        actual: null,
        forecast: null,
        previous: null,
        unit: null,
        change: null,
        changePercentage: null,
        description: `${lang === "ru" ? s.noteRu : s.noteEn} ${flags}${lang === "ru" ? "Источник" : "Source"}: ${s.src}`,
        hasDesc: true,
        period: q,
        origin: s.org,
        gk: s.gk,
        tags: s.tags,
      });
    }
  }
  return out.sort((a, b) => a.ts - b.ts || b.impact - a.impact || a.event.localeCompare(b.event));
}

const built: Partial<Record<"ru" | "en", CalEvent[]>> = {};

/** Commodity / agriculture events with UTC dates in [from, to] (inclusive). Titles are Russian for lang "ru", English otherwise. Pure, never throws. */
export function buildCommodityEvents(from: string, to: string, lang: CommodityLang = "ru"): CalEvent[] {
  const l = lang === "ru" ? "ru" : "en";
  let all = built[l];
  if (!all) all = built[l] = buildAll(l);
  return all.filter((e) => {
    const d = new Date(e.ts).toISOString().slice(0, 10);
    return d >= from && d <= to;
  });
}

/* ───────────── de-duplication against the TradingView feed ───────────── */

/** TradingView names the official layer replaces: when both carry the report on the same UTC day, the official one stays. */
const FEED_DUPLICATES: [RegExp, string][] = [
  [/^WASDE Report$/i, "agro.wasde"],
  [/^Quarterly Grain Stocks\b/i, "agro.grainstocks"],
];

/** Removes feed events (raw English names) that the commodity layer already covers (same report, same UTC day). */
export function dropOfficialDuplicates(main: readonly CalEvent[], commodity: readonly CalEvent[]): CalEvent[] {
  if (commodity.length === 0) return main.slice();
  const have = new Set(commodity.map((e) => `${e.gk}|${new Date(e.ts).toISOString().slice(0, 10)}`));
  return main.filter((e) => {
    const day = new Date(e.ts).toISOString().slice(0, 10);
    return !FEED_DUPLICATES.some(([re, gk]) => re.test(e.event.trim()) && have.has(`${gk}|${day}`));
  });
}
