import { eventId } from "./normalize";
import { addDays } from "./time";
import type { CalEvent } from "./types";

/*
 * RUSSIA LAYER (category "ru", country RU): the SCHEDULED macro releases, a static, hand-verified table. Dividend cut-offs, bond
 * coupons and company reports are NOT here: they are the separate "corp" layer (corporate.ts, T-Invest API).
 *
 * Why: TradingView's feed carries only a few Russian rows and nearly all of them with the lowest importance, so with the country filter
 * «Россия» the calendar looked empty. Everything here comes from the issuer's own published schedule (the URL is in `src` of the series
 * and in the description of every event) or from a rule the issuer states; rule-based items are APPROX (`a: true`): «(ориентировочно)»
 * in the title and importance <= 2.
 *
 * SOURCES (all checked on 2026-10-04) and HOW TO REFRESH (a yearly chore, ~30 minutes; run `npx tsx scripts/check-calendar-ru.ts`):
 *   - Bank of Russia key-rate meetings and the «Резюме обсуждения»: cbr.ru/dkp/cal_mp/ (2026 and 2027 are published in full; 13:30 MSK
 *     press release, 15:00 MSK press conference, «Среднесрочный прогноз» on every other meeting).
 *   - Bank of Russia publication schedule (inflation expectations, macro survey, enterprise monitoring, «Основные направления»,
 *     reserves, balance of payments, foreign trade, M2): cbr.ru/calendar/ (query UniDbQuery.year=2026|2027&UniDbQuery.period=4). The
 *     analytical part of it covers only ~3 months ahead (those are the EXACT items), the statistical part ~12 months.
 *   - Rosstat 2026: rosstat.gov.ru/storage/mediabank/Grafik_srochn_2026.docx («График выпуска срочных информаций и справок»: weekly and
 *     monthly CPI, PPI, industrial production, GDP) and Grafic_oper_public_2026.doc (the monthly «Социально-экономическое положение
 *     России»: unemployment, retail sales, wages). Rosstat's site needs the Russian root certificate. The 2027 schedule is not out yet
 *     (expected in the winter): only the weekly CPI (every Wednesday) is generated by rule, as APPROX.
 *   - Ministry of Finance OFZ auctions: minfin.gov.ru/ru/perfomance/public_debt/internal/operations/ofz/auction (a schedule per quarter,
 *     published on the last working day of the previous one; 2026 Q1-Q4 are in).
 * Times: MSK = UTC+3 all year (no DST). Rosstat gives no clock time in its schedules; its operational data come out at 19:00 MSK
 * (confirmed by the TradingView feed: 16:00 UTC), so that time is used and the description says where it comes from.
 * NOT included because no dates are published in advance: the Bank of Russia «Доклад о денежно-кредитной политике», the Ministry of
 * Finance budget execution (about the 10th), weekly reserves and the monetary base (they would flood the grid).
 */

export type RuLang = "ru" | "en" | "cn";

interface Item {
  /** date YYYY-MM-DD (Moscow) */
  d: string;
  /** clock time HH:MM MSK, overrides series.t */
  t?: string;
  /** period code, see periodLabel */
  p?: string;
  /** approximate date (rule of thumb) */
  a?: boolean;
  imp?: 1 | 2 | 3;
  /** extra sentence (ru / en) */
  x?: string;
  xe?: string;
}

interface Series {
  id: string;
  gk: string;
  tags: string[];
  impact: 1 | 2 | 3;
  ru: string;
  en: string;
  /** default clock time HH:MM MSK ("" = all-day) */
  t: string;
  org: string;
  src: string;
  noteRu: string;
  noteEn: string;
  /** raw TradingView names (country RU) that mean the same release: when the feed has one on the same UTC day, our item is dropped (the feed has the figures) */
  feed?: RegExp;
  items: Item[];
}

const MONTH_NOM = ["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"];
const MONTH_GEN = ["января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"];
const MONTH_EN = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const MON_EN = MONTH_EN.map((m) => m.slice(0, 3));

/**
 * Period code -> label (ru, en):
 *   M2026-09 a month, C2026-01..09 January-September cumulative, Q2026-2 a quarter, H2026-1 a half-year, Y2025 a year ("Y2025r": revised),
 *   D2026-10-01 «as of» a date, W2026-01-01~2026-01-12 a week (weekly CPI).
 */
export function periodLabel(code: string, lang: "ru" | "en"): string {
  const ru = lang === "ru";
  let m = /^M(\d{4})-(\d{2})$/.exec(code);
  if (m) return ru ? `${MONTH_NOM[+m[2] - 1]} ${m[1]}` : `${MONTH_EN[+m[2] - 1]} ${m[1]}`;
  m = /^C(\d{4})-(\d{2})\.\.(\d{2})$/.exec(code);
  if (m) return ru ? `январь–${MONTH_NOM[+m[3] - 1]} ${m[1]}` : `Jan–${MON_EN[+m[3] - 1]} ${m[1]}`;
  m = /^Q(\d{4})-(\d)$/.exec(code);
  if (m) return ru ? `${m[2]} кв. ${m[1]}` : `Q${m[2]} ${m[1]}`;
  m = /^H(\d{4})-(\d)$/.exec(code);
  if (m) return ru ? `${m[2]} п/г ${m[1]}` : `H${m[2]} ${m[1]}`;
  m = /^Y(\d{4})(r?)$/.exec(code);
  if (m) return ru ? `${m[1]} год${m[2] ? ", уточнённая оценка" : ""}` : `${m[1]}${m[2] ? ", revised" : ""}`;
  m = /^D(\d{4})-(\d{2})-(\d{2})$/.exec(code);
  if (m) return ru ? `на ${+m[3]} ${MONTH_GEN[+m[2] - 1]} ${m[1]}` : `as of ${MON_EN[+m[2] - 1]} ${+m[3]}, ${m[1]}`;
  m = /^W(\d{4})-(\d{2})-(\d{2})~(\d{4})-(\d{2})-(\d{2})$/.exec(code);
  if (m) {
    const [d1, m1, d2, m2] = [+m[3], +m[2], +m[6], +m[5]];
    if (ru) return m1 === m2 ? `${d1}–${d2} ${MONTH_GEN[m2 - 1]}` : `${d1} ${MONTH_GEN[m1 - 1]} – ${d2} ${MONTH_GEN[m2 - 1]}`;
    return m1 === m2 ? `${MON_EN[m2 - 1]} ${d1}–${d2}` : `${MON_EN[m1 - 1]} ${d1} – ${MON_EN[m2 - 1]} ${d2}`;
  }
  return "";
}

/* ───────────── calendar arithmetic (YYYY-MM-DD strings) ───────────── */

const dow = (d: string): number => new Date(`${d}T00:00:00Z`).getUTCDay(); // 0 Sunday
const iso = (y: number, m: number, d: number): string => new Date(Date.UTC(y, m - 1, d)).toISOString().slice(0, 10);

function lastWednesday(y: number, m: number): string {
  const last = addDays(iso(y, m + 1, 1), -1);
  return addDays(last, -((dow(last) - 3 + 7) % 7));
}

/** Rosstat's weekly CPI estimate comes out every Wednesday (the 2027 schedule is not published yet): the rule for [from, to]. */
export function weeklyCpiRule(from: string, to: string): Item[] {
  const out: Item[] = [];
  let d = from;
  while (dow(d) !== 3) d = addDays(d, 1);
  for (; d <= to; d = addDays(d, 7)) out.push({ d, a: true });
  return out;
}

/** Inflation expectations of the Bank of Russia: 2026 dates were Jun 24, Jul 28, Aug 26, Sep 29, Oct 28 (a Tue / Wed in the last week of the month): the last Wednesday. */
export function inflExpRule(from: string, to: string): Item[] {
  const out: Item[] = [];
  for (let y = +from.slice(0, 4); y <= +to.slice(0, 4); y++) {
    for (let m = 1; m <= 12; m++) {
      const d = lastWednesday(y, m);
      if (d >= from && d <= to) out.push({ d, a: true, p: `M${y}-${String(m).padStart(2, "0")}` });
    }
  }
  return out;
}

const items = (list: string, extra: Partial<Item> = {}): Item[] => list.split(/\s+/).filter(Boolean).map((d) => ({ d, ...extra }));
/** "2026-10-07:D2026-10-01 ..." -> items with a period code */
const withP = (list: string): Item[] =>
  list.split(/\s+/).filter(Boolean).map((s) => {
    const [d, p] = s.split(":");
    return { d, p };
  });

/* ───────────── the table ───────────── */

const CBR_RATE_URL = "https://www.cbr.ru/dkp/cal_mp/";
const CBR_CAL_URL = "https://www.cbr.ru/calendar/";
const ROSSTAT_URGENT = "https://rosstat.gov.ru/storage/mediabank/Grafik_srochn_2026.docx";
const ROSSTAT_OPER = "https://rosstat.gov.ru/storage/mediabank/Grafic_oper_public_2026.doc";
const MINFIN_URL = "https://minfin.gov.ru/ru/perfomance/public_debt/internal/operations/ofz/auction";

/** Board meetings on the key rate (cbr.ru/dkp/cal_mp/). F = a medium-term forecast is published at the meeting. */
export const CBR_MEETINGS = "2026-02-13:F 2026-03-20 2026-04-24:F 2026-06-19 2026-07-24:F 2026-09-11 2026-10-23:F 2026-12-18 2027-02-12:F 2027-03-19 2027-04-30:F 2027-06-11 2027-07-30:F 2027-09-10 2027-10-22:F 2027-12-17";
/** «Резюме обсуждения ключевой ставки» (the day with «Комментарий к среднесрочному прогнозу» is marked F). */
export const CBR_SUMMARIES = "2026-02-26:F 2026-04-01 2026-05-07:F 2026-07-01 2026-08-05:F 2026-09-23 2026-11-05:F 2026-12-30 2027-02-25:F 2027-03-31 2027-05-14:F 2027-06-24 2027-08-11:F 2027-09-22 2027-11-03:F 2027-12-29";

const meetingItems = (): Item[] =>
  CBR_MEETINGS.split(" ").map((s) => {
    const [d, f] = s.split(":");
    return f
      ? { d, x: "На этом заседании публикуется среднесрочный прогноз Банка России.", xe: "A medium-term forecast of the Bank of Russia is published after this meeting." }
      : { d };
  });
const summaryItems = (): Item[] =>
  CBR_SUMMARIES.split(" ").map((s) => {
    const [d, f] = s.split(":");
    return f
      ? { d, x: "В этот же день выходит «Комментарий к среднесрочному прогнозу Банка России».", xe: "The «Comment on the medium-term forecast» is published the same day." }
      : { d };
  });

/** Weekly CPI estimates of the official 2026 schedule: publication date / week start / week end. */
const WEEKLY_2026 =
  "2026-01-14/01-01/01-12 2026-01-21/01-13/01-19 2026-01-28/01-20/01-26 2026-02-04/01-27/02-02 2026-02-11/02-03/02-09 2026-02-18/02-10/02-16 2026-02-27/02-17/02-24 2026-03-04/02-25/03-02 2026-03-13/03-03/03-10 2026-03-18/03-11/03-16 2026-03-25/03-17/03-23 2026-04-01/03-24/03-30 2026-04-08/03-31/04-06 2026-04-15/04-07/04-13 2026-04-22/04-14/04-20 2026-04-29/04-21/04-27 2026-05-06/04-28/05-04 2026-05-15/05-05/05-12 2026-05-20/05-13/05-18 2026-05-27/05-19/05-25 2026-06-03/05-26/06-01 2026-06-10/06-02/06-08 2026-06-17/06-09/06-15 2026-06-24/06-16/06-22 2026-07-01/06-23/06-29 2026-07-08/06-30/07-06 2026-07-15/07-07/07-13 2026-07-22/07-14/07-20 2026-07-29/07-21/07-27 2026-08-05/07-28/08-03 2026-08-12/08-04/08-10 2026-08-19/08-11/08-17 2026-08-26/08-18/08-24 2026-09-02/08-25/08-31 2026-09-09/09-01/09-07 2026-09-16/09-08/09-14 2026-09-23/09-15/09-21 2026-09-30/09-22/09-28 2026-10-07/09-29/10-05 2026-10-14/10-06/10-12 2026-10-21/10-13/10-19 2026-10-28/10-20/10-26 2026-11-06/10-27/11-02 2026-11-11/11-03/11-09 2026-11-18/11-10/11-16 2026-11-25/11-17/11-23 2026-12-02/11-24/11-30 2026-12-09/12-01/12-07 2026-12-16/12-08/12-14 2026-12-23/12-15/12-21";

const weekly2026 = (): Item[] =>
  WEEKLY_2026.split(" ").map((s) => {
    const [d, a, b] = s.split("/");
    const y = d.slice(0, 4);
    const ya = +a.slice(0, 2) > +d.slice(5, 7) ? String(+y - 1) : y; // a week that starts in the previous year
    return { d, p: `W${ya}-${a}~${y}-${b}` };
  });

/** Minfin OFZ auction days with the indicative quarter plan, RUB bn (up to 10 years / 10 years and more). */
const OFZ_Q: [string, string, string][] = [
  ["2026-01-14 2026-01-21 2026-01-28 2026-02-04 2026-02-11 2026-02-18 2026-02-25 2026-03-04 2026-03-11 2026-03-18 2026-03-25", "1", "400 / 800"],
  ["2026-04-01 2026-04-08 2026-04-15 2026-04-22 2026-04-29 2026-05-06 2026-05-13 2026-05-20 2026-05-27 2026-06-03 2026-06-10 2026-06-17 2026-06-24", "2", "600 / 900"],
  ["2026-07-01 2026-07-08 2026-07-15 2026-07-22 2026-07-29 2026-08-05 2026-08-12 2026-08-19 2026-08-26 2026-09-02 2026-09-09 2026-09-16 2026-09-23 2026-09-30", "3", "900 / 600"],
  ["2026-10-07 2026-10-14 2026-10-21 2026-10-28 2026-11-11 2026-11-18 2026-11-25 2026-12-02 2026-12-09 2026-12-16 2026-12-23", "4", "1200 / 1250"],
];
const ofzItems = (): Item[] =>
  OFZ_Q.flatMap(([list, q, plan]) =>
    list.split(" ").map((d) => ({ d, x: `План квартала (индикативно, млрд руб., до 10 лет / от 10 лет): ${plan}. Время аукциона в графике не указано.`, xe: `Plan for Q${q} (indicative, RUB bn, up to 10 years / over 10 years): ${plan}. The schedule gives no auction time.` }))
  );

export const SERIES: Series[] = [
  /* ── Bank of Russia ── */
  {
    id: "cbr-rate", gk: "ru.cbr.rate", tags: ["rub", "bonds", "stocks"], impact: 3, t: "13:30", org: "Банк России", src: CBR_RATE_URL,
    ru: "Россия: решение Банка России по ключевой ставке", en: "Russia: Bank of Russia key rate decision",
    noteRu: "Заседание Совета директоров Банка России по ключевой ставке: пресс-релиз с решением в 13:30 мск, пресс-конференция Председателя в 15:00 мск.",
    noteEn: "Board of Directors meeting on the key rate: the press release with the decision at 13:30 Moscow time, the Governor's press conference at 15:00.",
    feed: /^Interest Rate Decision$/i, items: meetingItems(),
  },
  {
    id: "cbr-summary", gk: "cbr.keyrate", tags: ["rub", "bonds", "stocks"], impact: 2, t: "", org: "Банк России", src: CBR_RATE_URL,
    ru: "Россия: резюме обсуждения ключевой ставки Банка России", en: "Russia: Bank of Russia key rate discussion summary",
    noteRu: "Публикация итогов дискуссии членов Совета директоров на прошедшем заседании по ставке (примерно через две недели после решения).",
    noteEn: "Summary of the Board's discussion at the latest key rate meeting (about two weeks after the decision).",
    feed: /^Summary of the Key Rate Discussion$/i, items: summaryItems(),
  },
  {
    id: "cbr-ondkp", gk: "ru.cbr.ondkp", tags: ["rub", "bonds"], impact: 2, t: "", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: проект Основных направлений денежно-кредитной политики на 2027–2029 годы", en: "Russia: draft Guidelines for the monetary policy of 2027–2029",
    noteRu: "Банк России публикует проект «Основных направлений единой государственной денежно-кредитной политики на 2027 год и период 2028 и 2029 годов».",
    noteEn: "The Bank of Russia publishes the draft «Guidelines for the unified state monetary policy for 2027 and 2028–2029».",
    items: [{ d: "2026-08-31", x: "Первый проект.", xe: "First draft." }, { d: "2026-09-30", x: "Второй проект (направлен в Государственную Думу).", xe: "Second draft (sent to the State Duma)." }],
  },
  {
    id: "cbr-inflexp", gk: "ru.cbr.inflexp", tags: ["rub", "bonds"], impact: 2, t: "", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: инфляционные ожидания и потребительские настроения (Банк России)", en: "Russia: inflation expectations and consumer sentiment (Bank of Russia)",
    noteRu: "Ежемесячное исследование инФОМ по заказу Банка России: чего ждут от цен население и аналитики.",
    noteEn: "Monthly inFOM survey commissioned by the Bank of Russia: what households and analysts expect from prices.",
    items: [...withP("2026-07-28:M2026-07 2026-08-26:M2026-08 2026-09-29:M2026-09 2026-10-28:M2026-10"), ...inflExpRule("2026-11-01", "2027-12-31")],
  },
  {
    id: "cbr-macro", gk: "ru.cbr.macro", tags: ["rub", "bonds"], impact: 1, t: "", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: макроэкономический опрос Банка России", en: "Russia: Bank of Russia macroeconomic survey",
    noteRu: "Консенсус профессиональных аналитиков по ключевой ставке, инфляции, ВВП и курсу рубля.",
    noteEn: "Consensus of professional analysts on the key rate, inflation, GDP and the ruble.",
    items: items("2026-07-15 2026-09-02 2026-10-14"),
  },
  {
    id: "cbr-monitor", gk: "ru.cbr.monitor", tags: ["rub", "stocks"], impact: 1, t: "", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: мониторинг предприятий (Банк России)", en: "Russia: enterprise monitoring (Bank of Russia)",
    noteRu: "Опрос предприятий о спросе, ценах, инвестициях и ожиданиях: ранний индикатор состояния экономики.",
    noteEn: "Survey of companies on demand, prices, investment and expectations: an early gauge of the economy.",
    items: items("2026-07-15 2026-08-18 2026-09-15 2026-10-14"),
  },
  {
    id: "cbr-reserves", gk: "ru.cbr.reserves", tags: ["rub"], impact: 1, t: "16:00", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: международные резервы Банка России", en: "Russia: Bank of Russia international reserves",
    noteRu: "Ежемесячные данные о международных резервах на начало месяца (16:00 мск).", noteEn: "Monthly international reserves at the start of the month (16:00 Moscow time).",
    feed: /^Foreign Exchange Reserves$/i,
    items: withP("2026-10-07:D2026-10-01 2026-11-09:D2026-11-01 2026-12-07:D2026-12-01 2027-01-15:D2027-01-01 2027-02-05:D2027-02-01 2027-03-05:D2027-03-01 2027-04-07:D2027-04-01 2027-05-11:D2027-05-01 2027-06-07:D2027-06-01 2027-07-07:D2027-07-01"),
  },
  {
    id: "cbr-bop", gk: "ru.cbr.bop", tags: ["rub"], impact: 2, t: "16:00", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: оценка платёжного баланса (Банк России)", en: "Russia: balance of payments estimate (Bank of Russia)",
    noteRu: "Ежемесячная оценка платёжного баланса и счёта текущих операций с начала года (16:00 мск).", noteEn: "Monthly balance of payments and current account estimate, year to date (16:00 Moscow time).",
    items: withP("2026-10-15:C2026-01..08 2026-11-16:C2026-01..09 2026-12-15:C2026-01..10 2027-01-22:C2026-01..11 2027-02-15:C2026-01..12 2027-03-17:M2027-01 2027-04-14:C2027-01..02 2027-05-19:C2027-01..03 2027-06-15:C2027-01..04 2027-07-15:C2027-01..05 2027-08-16:C2027-01..06 2027-09-14:C2027-01..07 2027-10-15:C2027-01..08 2027-11-15:C2027-01..09 2027-12-15:C2027-01..10"),
  },
  {
    id: "cbr-trade", gk: "ru.cbr.trade", tags: ["rub", "oil"], impact: 1, t: "16:00", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: внешняя торговля товарами (Банк России)", en: "Russia: foreign trade in goods (Bank of Russia)",
    noteRu: "Экспорт, импорт и торговый баланс по методологии платёжного баланса (16:00 мск).", noteEn: "Exports, imports and the trade balance on the balance of payments basis (16:00 Moscow time).",
    feed: /^Balance of Trade$/i,
    items: withP("2026-10-12:M2026-08 2026-11-11:M2026-09 2026-12-11:M2026-10 2027-01-22:M2026-11 2027-02-11:M2026-12 2027-03-15:M2027-01 2027-04-12:M2027-02 2027-05-17:M2027-03 2027-06-11:M2027-04"),
  },
  {
    id: "cbr-m2", gk: "ru.cbr.m2", tags: ["rub"], impact: 1, t: "", org: "Банк России", src: CBR_CAL_URL,
    ru: "Россия: денежная масса М2 (Банк России)", en: "Russia: M2 money supply (Bank of Russia)",
    noteRu: "Денежная масса М2 (национальное определение) на начало месяца.", noteEn: "M2 money supply (national definition) at the start of the month.",
    feed: /^M2 Money Supply/i,
    items: withP("2026-10-20:D2026-10-01 2026-11-20:D2026-11-01 2026-12-18:D2026-12-01 2027-01-28:D2027-01-01 2027-02-18:D2027-02-01 2027-03-19:D2027-03-01 2027-04-20:D2027-04-01 2027-05-24:D2027-05-01 2027-06-21:D2027-06-01"),
  },
  /* ── Rosstat (19:00 MSK) ── */
  {
    id: "rs-cpiw", gk: "ru.rosstat.cpiw", tags: ["rub", "bonds", "stocks"], impact: 2, t: "19:00", org: "Росстат", src: ROSSTAT_URGENT,
    ru: "Россия: недельная инфляция (Росстат)", en: "Russia: weekly inflation (Rosstat)",
    noteRu: "Оценка индекса потребительских цен за неделю (по средам, 19:00 мск; в праздничные недели срок сдвигается).", noteEn: "Weekly consumer price index estimate (Wednesdays, 19:00 Moscow time; moved in holiday weeks).",
    items: [...weekly2026(), ...weeklyCpiRule("2027-01-13", "2027-12-31")],
  },
  {
    id: "rs-cpi", gk: "ru.rosstat.cpi", tags: ["rub", "bonds", "stocks"], impact: 3, t: "19:00", org: "Росстат", src: ROSSTAT_URGENT,
    ru: "Россия: инфляция за месяц, ИПЦ (Росстат)", en: "Russia: monthly CPI inflation (Rosstat)",
    noteRu: "Индекс потребительских цен за месяц: главный показатель для решений Банка России по ставке.", noteEn: "Monthly consumer price index: the key input for the Bank of Russia rate decisions.",
    feed: /^Inflation Rate (YoY|MoM)$/i,
    items: withP("2026-01-16:M2025-12 2026-02-13:M2026-01 2026-03-13:M2026-02 2026-04-10:M2026-03 2026-05-15:M2026-04 2026-06-10:M2026-05 2026-07-10:M2026-06 2026-08-12:M2026-07 2026-09-11:M2026-08 2026-10-09:M2026-09 2026-11-13:M2026-10 2026-12-09:M2026-11"),
  },
  {
    id: "rs-ppi", gk: "ru.rosstat.ppi", tags: ["rub", "stocks"], impact: 2, t: "19:00", org: "Росстат", src: ROSSTAT_URGENT,
    ru: "Россия: цены производителей промышленных товаров (Росстат)", en: "Russia: producer prices of industrial goods (Rosstat)",
    noteRu: "Индекс цен производителей промышленных товаров за месяц.", noteEn: "Monthly producer price index of industrial goods.",
    feed: /^PPI /i,
    items: withP("2026-01-28:M2025-12 2026-02-18:M2026-01 2026-03-18:M2026-02 2026-04-22:M2026-03 2026-05-20:M2026-04 2026-06-17:M2026-05 2026-07-22:M2026-06 2026-08-19:M2026-07 2026-09-16:M2026-08 2026-10-21:M2026-09 2026-11-18:M2026-10 2026-12-16:M2026-11"),
  },
  {
    id: "rs-ip", gk: "ru.rosstat.ip", tags: ["rub", "stocks"], impact: 2, t: "19:00", org: "Росстат", src: ROSSTAT_URGENT,
    ru: "Россия: промышленное производство (Росстат)", en: "Russia: industrial production (Rosstat)",
    noteRu: "Динамика промышленного производства (добыча, обработка, энергетика) с начала года и за месяц.", noteEn: "Industrial production (mining, manufacturing, utilities), year to date and for the month.",
    feed: /^Industrial Production/i,
    items: withP("2026-02-06:Y2025 2026-02-27:M2026-01 2026-03-25:C2026-01..02 2026-04-22:Q2026-1 2026-05-27:C2026-01..04 2026-06-24:C2026-01..05 2026-07-22:H2026-1 2026-08-26:C2026-01..07 2026-09-23:C2026-01..08 2026-10-28:C2026-01..09 2026-11-25:C2026-01..10 2026-12-23:C2026-01..11"),
  },
  {
    id: "rs-labor", gk: "ru.rosstat.labor", tags: ["rub", "bonds", "stocks"], impact: 2, t: "19:00", org: "Росстат", src: ROSSTAT_OPER,
    ru: "Россия: безработица, розничные продажи и зарплаты (Росстат)", en: "Russia: unemployment, retail sales and wages (Rosstat)",
    noteRu: "Ежемесячный доклад «Социально-экономическое положение России»: безработица, оборот розничной торговли, реальные зарплаты и доходы (данные по зарплатам — за предыдущий месяц).",
    noteEn: "Monthly «Socio-economic situation of Russia» report: unemployment, retail sales, real wages and incomes (wages are for the previous month).",
    feed: /^(Unemployment Rate|Retail Sales|Real Wage Growth)/i,
    items: withP("2026-02-06:M2025-12 2026-03-04:M2026-01 2026-04-01:M2026-02 2026-04-29:M2026-03 2026-06-03:M2026-04 2026-07-01:M2026-05 2026-07-29:M2026-06 2026-09-02:M2026-07 2026-09-30:M2026-08 2026-10-28:M2026-09 2026-12-02:M2026-10 2026-12-25:M2026-11"),
  },
  {
    id: "rs-gdpf", gk: "ru.rosstat.gdpf", tags: ["rub", "stocks"], impact: 2, t: "19:00", org: "Росстат", src: ROSSTAT_URGENT,
    ru: "Россия: ВВП, предварительная оценка (Росстат)", en: "Russia: GDP, preliminary estimate (Rosstat)",
    noteRu: "Справка о предварительной оценке динамики ВВП за квартал.", noteEn: "Preliminary estimate of the quarterly GDP dynamics.",
    items: withP("2026-05-15:Q2026-1 2026-08-12:Q2026-2 2026-11-13:Q2026-3"),
  },
  {
    id: "rs-gdp", gk: "ru.rosstat.gdp", tags: ["rub", "stocks"], impact: 3, t: "19:00", org: "Росстат", src: ROSSTAT_URGENT,
    ru: "Россия: ВВП, производство (Росстат)", en: "Russia: GDP, production (Rosstat)",
    noteRu: "Оценка ВВП по производству за квартал (в феврале и апреле — за прошлый год).", noteEn: "GDP by production for the quarter (February and April: the previous year).",
    feed: /^GDP Growth Rate/i,
    items: withP("2026-02-06:Y2025 2026-04-10:Y2025r 2026-06-17:Q2026-1 2026-09-11:Q2026-2 2026-12-11:Q2026-3"),
  },
  {
    id: "rs-gdpu", gk: "ru.rosstat.gdpu", tags: ["rub", "stocks"], impact: 2, t: "19:00", org: "Росстат", src: ROSSTAT_URGENT,
    ru: "Россия: ВВП, использование (Росстат)", en: "Russia: GDP, use (Rosstat)",
    noteRu: "Структура ВВП по использованию: потребление, инвестиции, экспорт, импорт.", noteEn: "GDP by expenditure: consumption, investment, exports, imports.",
    items: withP("2026-07-01:Q2026-1 2026-10-02:Q2026-2 2026-12-30:Q2026-3"),
  },
  /* ── Ministry of Finance ── */
  {
    id: "ofz-auction", gk: "ru.ofz.auction", tags: ["ofz", "bonds", "rub"], impact: 2, t: "", org: "Минфин России", src: MINFIN_URL,
    ru: "Россия: аукцион Минфина по размещению ОФЗ", en: "Russia: Ministry of Finance OFZ auction",
    noteRu: "Плановый аукцион Минфина по размещению облигаций федерального займа (по средам). График на квартал публикуется в последний рабочий день предыдущего.",
    noteEn: "Scheduled Ministry of Finance auction of federal loan bonds (OFZ, on Wednesdays). The quarter's schedule is published on the last working day of the previous one.",
    items: ofzItems(),
  },
];

/* ───────────── building events ───────────── */

const SUFFIX = { ru: " (ориентировочно)", en: " (approx.)" } as const;

export function toTs(date: string, hm: string): { ts: number; allDay: boolean } {
  const [y, m, d] = date.split("-").map(Number);
  if (!hm) return { ts: Date.UTC(y, m - 1, d), allDay: true };
  const [h, mi] = hm.split(":").map(Number);
  return { ts: Date.UTC(y, m - 1, d, h - 3, mi), allDay: false }; // MSK = UTC+3
}

export interface RuScheduled {
  series: string;
  gk: string;
  date: string;
  ts: number;
  allDay: boolean;
  approx: boolean;
  impact: 1 | 2 | 3;
  src: string;
  period: string | undefined;
}

export function russiaSchedule(): RuScheduled[] {
  const out: RuScheduled[] = [];
  for (const s of SERIES) {
    for (const it of s.items) {
      const { ts, allDay } = toTs(it.d, it.t ?? s.t);
      const base = it.imp ?? s.impact;
      out.push({ series: s.id, gk: s.gk, date: it.d, ts, allDay, approx: !!it.a, impact: (it.a ? Math.min(base, 2) : base) as 1 | 2 | 3, src: s.src, period: it.p });
    }
  }
  return out.sort((a, b) => a.ts - b.ts);
}

function buildAll(lang: "ru" | "en"): CalEvent[] {
  const out: CalEvent[] = [];
  for (const s of SERIES) {
    for (const it of s.items) {
      const { ts, allDay } = toTs(it.d, it.t ?? s.t);
      const q = it.p ? periodLabel(it.p, lang) : "";
      const title = `${lang === "ru" ? s.ru : s.en}${q ? `, ${q}` : ""}${it.a ? SUFFIX[lang] : ""}`;
      const extra = lang === "ru" ? it.x : it.xe;
      const flags =
        lang === "ru"
          ? `${it.a ? "Дата ориентировочная: выведена по правилу, график на этот период ещё не опубликован. " : ""}${!allDay && s.org === "Росстат" ? "Время 19:00 мск — сложившееся время выхода оперативных данных, в графике Росстата не указано. " : ""}`
          : `${it.a ? "Approximate date: derived from a rule, the schedule for this period is not published yet. " : ""}${!allDay && s.org === "Росстат" ? "19:00 Moscow time is the usual release time of the operational data; Rosstat's schedule gives none. " : ""}`;
      const base = it.imp ?? s.impact;
      out.push({
        id: eventId(ts, "RU", title),
        ts,
        allDay,
        country: "RU",
        currency: "RUB",
        event: title,
        category: "ru",
        impact: (it.a ? Math.min(base, 2) : base) as 1 | 2 | 3,
        actual: null,
        forecast: null,
        previous: null,
        unit: null,
        change: null,
        changePercentage: null,
        description: `${lang === "ru" ? s.noteRu : s.noteEn} ${extra ? extra + " " : ""}${flags}${lang === "ru" ? "Источник" : "Source"}: ${s.src}`,
        hasDesc: true,
        period: q || undefined,
        origin: s.org,
        gk: s.gk,
        tags: s.tags,
      });
    }
  }
  return out.sort((a, b) => a.ts - b.ts || b.impact - a.impact || a.event.localeCompare(b.event));
}

const built: Partial<Record<"ru" | "en", CalEvent[]>> = {};

/** Scheduled Russia events (Bank of Russia, Rosstat, Minfin) with UTC dates in [from, to] (inclusive). Russian titles for lang "ru", English otherwise. Pure, never throws. */
export function buildRussiaScheduled(from: string, to: string, lang: RuLang = "ru"): CalEvent[] {
  const l = lang === "ru" ? "ru" : "en";
  let all = built[l];
  if (!all) all = built[l] = buildAll(l);
  return all.filter((e) => {
    const d = new Date(e.ts).toISOString().slice(0, 10);
    return d >= from && d <= to;
  });
}

/* ───────────── de-duplication against the TradingView feed ───────────── */

/** gk -> the feed names that mean the same release (taken from the series table). */
const FEED_BY_GK = new Map<string, RegExp[]>();
for (const s of SERIES) {
  if (!s.feed) continue;
  const l = FEED_BY_GK.get(s.gk) ?? [];
  l.push(s.feed);
  FEED_BY_GK.set(s.gk, l);
}

/**
 * Our dates and importance are right, but the feed carries the figures (forecast / actual / previous): when the feed has the same Russian
 * release on the same UTC day, the feed's event stays and ours is dropped. Feed events are the raw (English) ones.
 */
export function dropCoveredByFeed(layer: readonly CalEvent[], feed: readonly CalEvent[]): CalEvent[] {
  const ru = feed.filter((f) => f.country === "RU" && f.category !== "ru");
  if (ru.length === 0) return layer.slice();
  const day = (ts: number) => new Date(ts).toISOString().slice(0, 10);
  const have = ru.map((f) => ({ d: day(f.ts), name: f.event.trim() }));
  return layer.filter((e) => {
    const res = e.gk ? FEED_BY_GK.get(e.gk) : undefined;
    if (!res) return true;
    const d = day(e.ts);
    return !have.some((h) => h.d === d && res.some((re) => re.test(h.name)));
  });
}
